### ISSUE TITLE
Add instructions for how to use this in VScode + Devcontainer local environment

### ISSUE THREAD

**Issue by leestott** [microsoft/codespaces-project-template-py#24]
see https://github.com/Microsoft/vscode-remote-try-python

This is useful for student who want to use the resources offline.

**Comment by alfredodeza** [comment]
Since we are concentrating in Codespaces this would require adding significant instructions to the documentation on how to:

- Install and configure Docker locally
- Install the Remote Containers extension
- Open the repository and connect to the remote container

Since there are other resources for this type of setup, would you be OK if we add it to the resources section as a separate link instead?

**Comment by alfredodeza** [comment]
Added section about Dev Containers at the end in the resources section
